### ISSUE TITLE
Error : Factory cannot be converted to Handler

### ISSUE THREAD

**Issue by AskMeCode** [yusufcakmak/ExoPlayerSample#10]
at this ligne:
TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory );

**Comment by yusufcakmak** [comment]
are you using my example ? if you are not using, can you provide more detail ?

**Comment by AskMeCode** [comment]
Yes i us you example
