### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Angelk90** [yusufcakmak/ExoPlayerSample#16]
@yusufcakmak : 
how can I add the split-screen thing, that if you click on the video to the right / left you can go back in the video.
I would like to do something like this: https://drive.google.com/file/d/1Vg-C_LYVvCW9gqXpfGPB5Fg6h_ekAx29/view

**Comment by soonsam123** [comment]
1. Add two simple views to determine if the user clicked left or right;
2. Then you implement DoubleTap on the views, follow this [article](https://stackoverflow.com/questions/4804798/doubletap-in-android);
3. You move the position of the player to + 10 seconds using the following code:

```
long currentPosition = player.getCurrentPosition();
player.seekto(currentPosition + 10000);
 ```

10000 miliseconds = 10 seconds

You can see an example in [this project](https://github.com/soonsam123/UsagesOfExoplayer/blob/master/app/src/main/java/com/soon/karat/exoplayer/complex_examples/PlayerActivity.java#L165).
