### ISSUE TITLE
NullPointerException when playing a particular HLS source 

### ISSUE THREAD

**Issue by newandroidboy88** [yusufcakmak/ExoPlayerSample#2]
When playing a HLS .m3u8 akamai hd live streaming url in exoplayer following error occured (Actually it works Yesterday but not today)

java.lang.NullPointerException: Attempt to invoke virtual method 'long com.google.android.exoplayer2.source.CompositeSequenceableLoader.getNextLoadPositionUs()' on a null object reference at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.getNextLoadPositionUs(HlsMediaPeriod.java:216) at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:1080)  at com.google.android.exoplayer2.ExoPlayerImplInternal.handleContinueLoadingRequested(ExoPlayerImplInternal.java:1076)  at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:289)  at android.os.Handler.dispatchMessage(Handler.java:98)  at android.os.Looper.loop(Looper.java:148)   at android.os.HandlerThread.run(HandlerThread.java:61)  at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by newandroidboy88** [comment]
my code

import android.app.Activity;
import android.content.Context;
import android.database.ContentObserver;
import android.media.AudioManager;
import android.net.Uri;
import android.os.Bundle;
import android.os.Environment;
import android.os.Handler;
import android.os.SystemClock;
import android.util.Log;
import android.view.MotionEvent;
import android.view.View;
import android.widget.Button;

import com.google.android.exoplayer2.C;
import com.google.android.exoplayer2.DefaultLoadControl;
import com.google.android.exoplayer2.ExoPlaybackException;
import com.google.android.exoplayer2.ExoPlayer;
import com.google.android.exoplayer2.ExoPlayerFactory;
import com.google.android.exoplayer2.Format;
import com.google.android.exoplayer2.SimpleExoPlayer;
import com.google.android.exoplayer2.Timeline;
import com.google.android.exoplayer2.extractor.DefaultExtractorsFactory;
import com.google.android.exoplayer2.source.ExtractorMediaSource;
import com.google.android.exoplayer2.source.MediaSource;
import com.google.android.exoplayer2.source.MergingMediaSource;
import com.google.android.exoplayer2.source.SingleSampleMediaSource;
import com.google.android.exoplayer2.source.hls.HlsMediaSource;
import com.google.android.exoplayer2.trackselection.AdaptiveVideoTrackSelection;
import com.google.android.exoplayer2.trackselection.DefaultTrackSelector;
import com.google.android.exoplayer2.trackselection.TrackSelection;
import com.google.android.exoplayer2.trackselection.TrackSelections;
import com.google.android.exoplayer2.trackselection.TrackSelector;
import com.google.android.exoplayer2.upstream.BandwidthMeter;
import com.google.android.exoplayer2.upstream.DataSource;
import com.google.android.exoplayer2.upstream.DefaultBandwidthMeter;
import com.google.android.exoplayer2.upstream.DefaultDataSourceFactory;
import com.google.android.exoplayer2.upstream.TransferListener;
import com.google.android.exoplayer2.util.MimeTypes;
import com.google.android.exoplayer2.util.Util;
import com.google.android.exoplayer2.video.VideoRendererEventListener;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.text.NumberFormat;
import java.util.Locale;

public class CustomVideoPlayerActivity extends Activity  {

    private Handler mainHandler;
    private Timeline.Window window;
    private CustomExoPlayerView simpleExoPlayerView;

    private DataSource.Factory mediaDataSourceFactory;
    private SimpleExoPlayer player;
    private DefaultTrackSelector trackSelector;

    private boolean shouldAutoPlay;
    private int playerWindow;
    private long playerPosition;
    private BandwidthMeter bandwidthMeter;
    private DefaultExtractorsFactory extractorsFactory;


    Handler volumeControl=new Handler();
    MediaSource mediaSource;
    Format textFormat;
    MediaSource subtitleSource;
    MergingMediaSource mergedSource;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_custom_video_player);

        shouldAutoPlay = true;
        bandwidthMeter = new DefaultBandwidthMeter();
        mediaDataSourceFactory = new DefaultDataSourceFactory(this, Util.getUserAgent(this, "ss"), (TransferListener<? super DataSource>) bandwidthMeter);
        mainHandler = new Handler();
        window = new Timeline.Window();
        simpleExoPlayerView = (CustomExoPlayerView) findViewById(R.id.player_view);
        simpleExoPlayerView.requestFocus();
        TrackSelection.Factory videoTrackSelectionFactory =
                new AdaptiveVideoTrackSelection.Factory(bandwidthMeter);
        trackSelector = new DefaultTrackSelector(mainHandler, videoTrackSelectionFactory);
        player = ExoPlayerFactory.newSimpleInstance(this, trackSelector, new DefaultLoadControl(),
                null, false);
        simpleExoPlayerView.setPlayer(player);

        player.setPlayWhenReady(shouldAutoPlay);

        extractorsFactory = new DefaultExtractorsFactory();
        /*MediaSource mediaSource = new ExtractorMediaSource(Uri.fromFile(dst),
        mediaDataSourceFactory, extractorsFactory, null, null);*/
        MediaSource mediaSource = new HlsMediaSource(Uri.parse(""),  //here i given my .m3u8 akamai live Streaming hsl 
                mediaDataSourceFactory, mainHandler, null);
        player.prepare(mediaSource);
    }

    private boolean copyFile(File src,File dst)throws IOException{
        if(src.getAbsolutePath().toString().equals(dst.getAbsolutePath().toString())){

            return true;

        }else{
            InputStream is=new FileInputStream(src);
            OutputStream os=new FileOutputStream(dst);
            byte[] buff=new byte[1024];
            int len;
            while((len=is.read(buff))>0){
                os.write(buff,0,len);
            }
            is.close();
            os.close();
        }
        return true;
    }





    @Override
    public void onStop() {
        super.onStop();
        if (Util.SDK_INT > 23) {
            releasePlayer();
        }

    }

    private void releasePlayer() {
        System.out.println("release Player called");
        if (player != null) {
            shouldAutoPlay = player.getPlayWhenReady();
            playerWindow = player.getCurrentWindowIndex();
            playerPosition = C.TIME_UNSET;
            Timeline timeline = player.getCurrentTimeline();
            if (timeline != null && timeline.getWindow(playerWindow, window).isSeekable) {
                playerPosition = player.getCurrentPosition();
            }
            player.release();
            player = null;
            trackSelector = null;
        }
    }

   


}

**Comment by yusufcakmak** [comment]
hello, your code seems like working, can you try another stream link ? you can try with https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8 

are you sure working your stream link ? if you are, can you provide to me, I can try.

**Comment by newandroidboy88** [comment]
I have enclosed the HLS Live Streaming Url below 
`http://bbg_syn_hls_demo-i.akamaihd.net/hls/live/207515/event/index.m3u8 ` 
It was working on some device and not working in other devices


throws same error above or source error

**Comment by yusufcakmak** [comment]
Which devices have problems? I have not encountered any problems in my tests.

**Comment by newandroidboy88** [comment]
Actually Url was working in Nexus 7 Tablet Device but not working when i run the same code in Some other device it was working in that device.After that again i run in nexus 7 Device it not working

**Comment by yusufcakmak** [comment]
I don't understand why it is working like that. I hope you will fix it.

**Comment by newandroidboy88** [comment]
In samsung note 3 its not working .can u check with  one
