### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by yusufcakmak** [yusufcakmak/ExoPlayerSample#24]
update readme for kotlin changes

**Comment by Arnaudp767** [comment]
Any chance to have an upgrade to 2.9 in Java version ?

**Comment by yusufcakmak** [comment]
I will rewrite this project, I'm going to separate the Kotlin and java versions. I'll try to settle next weekend.

**Comment by Arnaudp767** [comment]
Fine !

I tried on my side to update one of your previous project.
`mediaDataSourceFactory = new DefaultDataSourceFactory(this, Util.getUserAgent(this, "mediaPlayerSample"), (TransferListener<? super DataSource>) bandwidthMeter);`

error: type TransferListener does not take parameters

Any ideas ?
