### ISSUE TITLE
buttons

### ISSUE THREAD

**Issue by gladiator2b** [yusufcakmak/ExoPlayerSample#27]
Hello, how to have 2 buttons with links instead of a button as in your example

**Comment by yusufcakmak** [comment]
if you asking for the video sample, you can override xml files and changed how you want.

**Comment by gladiator2b** [comment]
it is for the file radio player example: you put this link companion object {
         const val RADIO_URL = "http://uk7.internet-radio.com:8226"
is it possible to have a second button with another link

**Comment by gladiator2b** [comment]
is it possible to have 1 link with button 1 and a second link with button 2
exemple button 1 "http://uk7.internet-radio.com:8226" button 2 "http://uk7.internet-radio.com:8227"

**Comment by yusufcakmak** [comment]
there are some options, you can change media source or you can use playlist

**Comment by gladiator2b** [comment]
I would need each button a different link other buttons
