### ISSUE TITLE
ProgressiveMediaSource not found

### ISSUE THREAD

**Issue by rezznov** [yusufcakmak/ExoPlayerSample#28]
First of all i gotta say, man thanks you saved my day. your code works like charm but there is something I wanted to know.
at line 31 of VideoPlayerActivity.kt, the ide does not recognize ProgressiveMediaSource class.
I'm using the full Exoplayer dependency v2.9.6 witch is compatible with support library.
my question is that why ProgressiveMediaSource  is not found by Android Studio?
I used just ExtractorMediaSource insted of ExtractorMediaSource like what android codelab tutorial did.

**Comment by yusufcakmak** [comment]
If you want to use ProgressiveMediaSource, you need to update the ExoPlayer version. (r2.10.4)

if you want to use v2.9.6, you can use ExtractorMediaSource. 

trackSelector = DefaultTrackSelector(videoTrackSelectionFactory)
val mediaSource = ExtractorMediaSource.Factory(mediaDataSourceFactory).createMediaSource(Uri.parse("http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"))

player = ExoPlayerFactory.newSimpleInstance(this, trackSelector)
