### ISSUE TITLE
about RTSP 

### ISSUE THREAD

**Issue by CMingTseng** [yusufcakmak/ExoPlayerSample#30]
Dear Sir

i clone your project 

and then check it 

the project not dependencies any  RTSP library  !!

it can play RTSP ?

if you can add RTSP

can ref this project  https://github.com/warren-bank/Android-RTSP-IPCam-Viewer/tree/dev/c516740

but need modify some class (because  the rtsp not contain Google OEM ExoPlayer library .this project is mixed & hacked  )

THX

**Comment by yusufcakmak** [comment]
MediaExtractor doesn't support RTSP. you can look at this issue -> https://github.com/google/ExoPlayer/issues/55

also yes, you can support and play but there some works for that. Unfortunately, I don't have time for this. But I will try when I got free time.

**Comment by CMingTseng** [comment]
@yusufcakmak 

as your link

https://github.com/google/ExoPlayer/issues/55

you can see  

https://github.com/google/ExoPlayer/issues/55#issuecomment-252356941

https://github.com/google/ExoPlayer/issues/6474#issuecomment-535414573

https://github.com/google/ExoPlayer/pull/3854

https://github.com/google/ExoPlayer/pull/6518

just  google do not merge !!

THX
