### ISSUE TITLE
MediaSource

### ISSUE THREAD

**Issue by wxflint** [yusufcakmak/ExoPlayerSample#31]
A bit new to this, am i suppose to remove some code in VideoPlayerActivity.kt and add the code below to play m3u8 files?
Thanks.

```
MediaSource mediaSource = new HlsMediaSource(Uri.parse("https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8"),
                mediaDataSourceFactory, mainHandler, null);
```

**Comment by yusufcakmak** [comment]
It depends on your media source. You can choose a media source according to your media.
