### ISSUE TITLE
Where is CustomPlaybackControlView

### ISSUE THREAD

**Issue by azurh** [yusufcakmak/ExoPlayerSample#5]
As stated in readme:

> I created CustomExoPlayerView and CustomPlaybackControlView classes. You can use custom playback controls easily.

I can't find the custom classes in the project.

**Comment by yusufcakmak** [comment]
sorry for old docs, you don't need custom classes anymore. If you are using 2.4 + you can create xml files and change them.

https://github.com/google/ExoPlayer/tree/release-v2/library/ui/src/main/res/layout
