### ISSUE TITLE
video player controls screenshot

### ISSUE THREAD

**Issue by bluemix** [yusufcakmak/ExoPlayerSample#6]
hello, 
it would be a good idea to include a screenshot of the player,
because, I had to clone and run the project on my machine in 
order to see how it locks.
i hope you can include the attached images in the REAME.md 
so that users have an overview of how it locks.
thanks :)

![screenshot_1506787091](https://user-images.githubusercontent.com/3332274/31047374-100812a2-a612-11e7-9c86-8a25ba21ac8b.png)

**Comment by yusufcakmak** [comment]
yes, you are right. I will add screenshots for default and custom player views. thanks :)

**Comment by yusufcakmak** [comment]
I added screenshots and little information.

**Comment by bluemix** [comment]
thanks dear 👍
